### ISSUE TITLE
Websocket URL

### ISSUE THREAD

**Issue by Adzter** [luker2009/RedRobin#1]
Using the latest Github version as well as having request/websocket installed it's seemingly unable to grab the robin_websocket_url from the url: "https://www.reddit.com/robin". (Starting on line 256).

> throw new Error('You must specify a full WebSocket URL, including protocol.');
> ^
> Error: You must specify a full WebSocket URL, including protocol.
>     at WebSocketClient.connect (C:\removed\node_modules\websocket\lib\WebSocketClient.js:138:15)
>     at Request._callback (C:\removed\main.js:126:15)
>     at Request.self.callback (C:\removed\node_modules\request\request.js:199:22)
>     at emitTwo (events.js:87:13)
>     at Request.emit (events.js:172:7)
>     at Request.<anonymous> (C:\removed\request\request.js:1036:10)
>     at emitOne (events.js:82:20)
>     at Request.emit (events.js:169:7)
>     at IncomingMessage.<anonymous> (C:\removed\request\request.js:963:12)
>     at emitNone (events.js:72:20)
> `

**Comment by Allymonies** [comment]
This error is usually due to incorrect login details, I'll update it to make sure the login succeeds soon.

If you're sure the details in config.json are correct then I'm not sure what the issue is.

**Comment by Adzter** [comment]
I didn't realise that you have to manually join a chat room. Apologies.

Logging in on Chrome, joining a chatroom then running the script seems to have it fully working now.

**Comment by Allymonies** [comment]
Ah yeah, I need to make it automatically join a new room as well.

EDIT: As of v1.5 login is checked and rooms are automatically joined.
